version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=lireddit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis

  server:
    build:
      context: ./server
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lireddit
      - REDIS_URL=redis:6379
      - PORT=4000
      - SESSION_SECRET=qowiueojwojfalksdjoqiwueo
      - CORS_ORIGIN=http://${HOST_SERVER_IP}:3000
    depends_on:
      - db
      - redis

  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_GRAPHQL_SERVER_URL=http://${HOST_SERVER_IP}:4000/graphql
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_GRAPHQL_SERVER_URL=http://server:4000/graphql
    depends_on:
      - server
