version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=reddut
      - POSTGRES_USER=reddut
      - POSTGRES_PASSWORD=reddut
  redis:
    image: redis
  server:
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgresql://reddut:reddut@db:5432/reddut
      - REDIS_URL=redis:6379
      - PORT=4000
      - SESSION_SECRET=qowiueojwojfalksdjoqiwueo
      - CORS_ORIGIN=http://proxy
    depends_on:
      - db
      - redis
  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_GRAPHQL_SERVER_URL=http://${HOST_SERVER_IP}/graphql
    depends_on:
      - server
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
      - server
